{
    "openapi": "3.0.0",
    "info": {
        "version": "0.0.1",
        "title": "Web Analytics Italia API",
        "description": "Questa interfaccia API si riferisce alle operazioni che le Pubbliche Amministrazioni possono eseguire in interoperabilit√† per gestire utenti e siti di WAI.",
        "contact": {
            "name": "AGID - Web Analytics Italia",
            "url": "https://webanalytics.italia.it/contacts",
            "email": "wai@agid.gov.it"
        }
    },
    "servers": [],
    "paths": {
        "/portal/users": {
            "post": {
                "tags": ["Utenti"],
                "summary": "Crea un nuovo utente",
                "operationId": "addUser",
                "requestBody": {
                    "description": "Dati dell'utente da creare",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/AddUserRequest"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Dati dell'utente",
                        "headers": {
                            "Location": {
                                "schema": {
                                    "type": "string",
                                    "format": "uri"
                                },
                                "description": "Uri del nuovo utente"
                            }
                        },
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UserInfo"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "tags": ["Utenti"],
                "summary": "Fornisce l'elenco degli utenti",
                "operationId": "getUsers",
                "responses": {
                    "200": {
                        "description": "Elenco degli utenti",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UserInfoArray"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/portal/users/{fn}": {
            "parameters": [
                { "$ref": "#/components/parameters/FiscalNumberInPath" }
            ],
            "get": {
                "tags": ["Utenti"],
                "summary": "Fornisce i dati dell'utente specificato",
                "operationId": "getUser",
                "responses": {
                    "200": {
                        "description": "Dati dell'utente",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UserInfo"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "tags": ["Utenti"],
                "summary": "Modifica i dati dell'utente specificato",
                "operationId": "patchUser",
                "requestBody": {
                    "description": "Dati dell'utente da modificare",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/PatchUserRequest"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Dati dell'utente",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UserInfo"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": ["Utenti"],
                "summary": "Elimina l'utente specificato",
                "operationId": "deleteUser",
                "responses": { "204": { "description": "Dati dell'utente" } }
            }
        },
        "/portal/users/{fn}/suspend": {
            "parameters": [
                { "$ref": "#/components/parameters/FiscalNumberInPath" }
            ],
            "patch": {
                "tags": ["Utenti"],
                "summary": "Sospende l'utente specificato",
                "operationId": "suspendUser",
                "responses": {
                    "200": {
                        "description": "Dati dell'utente",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UserInfo"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/portal/users/{fn}/reactivate": {
            "parameters": [
                { "$ref": "#/components/parameters/FiscalNumberInPath" }
            ],
            "patch": {
                "tags": ["Utenti"],
                "summary": "Riattiva l'utente specificato",
                "operationId": "reactivateUser",
                "responses": {
                    "200": {
                        "description": "Dati dell'utente",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UserInfo"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/portal/sites": {
            "post": {
                "tags": ["Siti web"],
                "summary": "Crea un nuovo sito web",
                "operationId": "addWebsite",
                "requestBody": {
                    "description": "Dati del sito web da creare",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/AddWebsiteRequest"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Dati del sito web",
                        "headers": {
                            "Location": {
                                "schema": {
                                    "type": "string",
                                    "format": "uri"
                                },
                                "description": "Uri del nuovo sito web"
                            }
                        },
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/WebsiteInfo"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "tags": ["Siti web"],
                "summary": "Restituisce l'elenco dei siti associati all'amministrazione",
                "operationId": "getWebsites",
                "responses": {
                    "200": {
                        "description": "Array dei siti",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/WebsiteInfoArray"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/portal/sites/{website}": {
            "parameters": [{ "$ref": "#/components/parameters/SlugInPath" }],
            "get": {
                "tags": ["Siti web"],
                "summary": "Fornisce i dati del sito web specificato",
                "operationId": "getWebsite",
                "responses": {
                    "200": {
                        "description": "Dati del sito web",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/WebsiteInfo"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "tags": ["Siti web"],
                "summary": "Modifica un sito web specificato",
                "operationId": "patchWebsite",
                "requestBody": {
                    "description": "Dati del sito web da modificare",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/AddWebsiteRequest"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Dati del sito web",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/WebsiteInfo"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/portal/sites/{website}/archive": {
            "parameters": [{ "$ref": "#/components/parameters/SlugInPath" }],
            "patch": {
                "tags": ["Siti web"],
                "summary": "Archivia il sito web specificato",
                "operationId": "archiveWebsite",
                "responses": {
                    "200": {
                        "description": "Dati del sito web",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ArchiveWebsite"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/portal/sites/{website}/unarchive": {
            "parameters": [{ "$ref": "#/components/parameters/SlugInPath" }],
            "patch": {
                "tags": ["Siti web"],
                "summary": "Ripristina il sito web specificato",
                "operationId": "unarchiveWebsite",
                "responses": {
                    "200": {
                        "description": "Dati del sito web",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UnarchiveWebsite"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/portal/sites/{website}/check": {
            "parameters": [{ "$ref": "#/components/parameters/SlugInPath" }],
            "get": {
                "tags": ["Siti web"],
                "summary": "Verifica l'attivazione del sito web specificato",
                "operationId": "checkWebsite",
                "responses": {
                    "304": {
                        "description": "Sito web non attivo"
                    }
                }
            }
        },
        "/portal/sites/{website}/js-snippet": {
            "parameters": [{ "$ref": "#/components/parameters/SlugInPath" }],
            "get": {
                "tags": ["Siti web"],
                "summary": "Fornisce lo snippet javascript del sito web specificato",
                "operationId": "websiteJsSnippet",
                "responses": {
                    "200": {
                        "description": "Snippet javascript del sito web specificato",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/JsSnippet"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "parameters": {
            "SlugInPath": {
                "in": "path",
                "required": true,
                "name": "website",
                "schema": {
                    "$ref": "#/components/schemas/WebsiteSlug"
                }
            },
            "FiscalNumberInPath": {
                "in": "path",
                "required": true,
                "name": "fn",
                "schema": {
                    "$ref": "#/components/schemas/FiscalNumber"
                }
            }
        },
        "schemas": {
            "WebsiteSlug": {
                "type": "string",
                "format": "^\\w+$"
            },
            "WebsiteType": {
                "type": "string",
                "description": "Tipologia di sito",
                "enum": ["site_type_1", "site_type_2", "site_type_3"]
            },
            "AddWebsiteRequest": {
                "required": ["name", "url", "type", "permissions"],
                "properties": {
                    "name": {
                        "description": "Nome del sito",
                        "type": "string",
                        "pattern": "^(?!\\s*$).+"
                    },
                    "url": {
                        "description": "Url del sito",
                        "type": "string",
                        "format": "uri"
                    },
                    "permissions": {
                        "$ref": "#/components/schemas/WebsiteInfoPermisionObject"
                    },
                    "type": {
                        "$ref": "#/components/schemas/WebsiteType"
                    }
                },
                "example": {
                    "name": "WebAnalytics Italia",
                    "url": "https://webanalytics.italia.it",
                    "type": "site_type_1",
                    "permissions": {
                        "userId": ["MANAGE_ANALYTICS"]
                    }
                }
            },
            "WebsiteInfoPermisionObject": {
                "type": "object",
                "required": ["userId"],
                "properties": {
                    "userId": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "AddWebsiteResponse": {
                "type": "object",
                "required": ["id", "name", "url", "analytics_id", "slug"],
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    },
                    "analytics_id": {
                        "type": "integer"
                    },
                    "slug": {
                        "type": "string"
                    }
                },
                "example": {
                    "id": 1,
                    "name": "Agenzia per L'Italia Digitale",
                    "url": "www.agid.gov.it",
                    "analytics_id": 2,
                    "slug": "wwwagidgovit"
                }
            },
            "UserSuspendObject": {
                "type": "object",
                "required": ["result", "user_name", "status"],
                "properties": {
                    "result": {
                        "type": "string"
                    },
                    "user_name": {
                        "type": "string"
                    },
                    "status_description": {
                        "type": "string"
                    }
                },
                "example": {
                    "result": "ok",
                    "id": "4427f41c-de93-4ce7-becc-99902a38799e",
                    "user_name": "Luisa Test",
                    "status": "SUSPENDED",
                    "status_description": "sospeso",
                    "trashed": false,
                    "administration": "Agenzia per L'Italia Digitale"
                }
            },
            "WebsiteInfoArray": {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/AddWebsiteResponse"
                }
            },
            "WebsiteInfo": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    },
                    "analytics_id": {
                        "type": "integer"
                    },
                    "slug": {
                        "type": "string"
                    }
                },
                "example": {
                    "id": 1,
                    "name": "Agenzia per L'Italia Digitale",
                    "url": "www.agid.gov.it",
                    "type": 0,
                    "public_administration_id": 1,
                    "analytics_id": 2,
                    "slug": "wwwagidgovit",
                    "status": 1,
                    "created_at": "2020-07-21T17:32:28Z",
                    "updated_at": "2020-07-21T17:32:28Z",
                    "deleted_at": "2020-07-21T17:32:28Z"
                }
            },
            "ArchiveWebsite": {
                "type": "object",
                "required": ["slug"],
                "example": {
                    "result": "ok",
                    "id": "wwwagidgovit",
                    "website_name": "Agenzia per L'Italia Digitale",
                    "status": "ARCHIVED",
                    "status_description": "archiviato",
                    "trashed": false
                }
            },
            "UnarchiveWebsite": {
                "type": "object",
                "required": ["slug"],
                "example": {
                    "result": "ok",
                    "id": "wwwagidgovit",
                    "website_name": "Agenzia per L'Italia Digitale",
                    "status": "ACTIVE",
                    "status_description": "attivo",
                    "trashed": false
                }
            },
            "JsSnippet": {
                "example": {
                    "result": "ok",
                    "id": "wwwagidgovit",
                    "name": "Agenzia per L'Italia Digitale",
                    "javascriptSnippet": "<!-- Matomo -->\n<script type=\"text/javascript\">\n  var _paq = window._paq || [];\n  /* tracker methods like \"setCustomDimension\" should be called before \"trackPageView\" */\n  _paq.push(['trackPageView']);\n  _paq.push(['enableLinkTracking']);\n  (function() {\n    var u=\"https://172.22.0.10/\";\n    _paq.push(['setTrackerUrl', u+'matomo.php']);\n    _paq.push(['setSiteId', '3']);\n    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];\n    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);\n  })();\n</script>\n<!-- End Matomo Code -->"
                }
            },
            "FiscalNumber": {
                "type": "string",
                "minLength": 16,
                "maxLength": 16,
                "pattern": "[A-Z0-9]{16}"
            },
            "AddUserRequest": {
                "$ref": "#/components/schemas/UserInfo"
            },
            "PatchUserRequest": {
                "type": "object",
                "required": ["fiscalNumber"],
                "properties": {
                    "fiscalNumber": {
                        "$ref": "#/components/schemas/FiscalNumber"
                    }
                },
                "example": {
                    "fiscalNumber": "ZRSGLC89D05H501J"
                }
            },
            "UserStatus": {
                "type": "string",
                "description": "Stato dell'utente",
                "enum": ["activated", "not_activated"]
            },
            "UserInfoArray": {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/UserInfo"
                }
            },
            "UserInfoPermissions": {
                "type": "object",
                "required": ["siteId"],
                "properties": {
                    "siteId": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "UserInfo": {
                "type": "object",
                "required": [
                    "firstName",
                    "lastName",
                    "email",
                    "fiscalNumber",
                    "permissions"
                ],
                "properties": {
                    "firstName": {
                        "type": "string"
                    },
                    "lastName": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "permissions": {
                        "$ref": "#/components/schemas/UserInfoPermissions"
                    },
                    "fiscalNumber": {
                        "$ref": "#/components/schemas/FiscalNumber"
                    }
                },
                "example": {
                    "firstName": "User",
                    "lastName": "Example",
                    "email": "name@email.com",
                    "fiscalNumber": "ZRSGLC89D05H501J",
                    "permissions": {
                        "siteId" : ["manage-analytics"]
                    }
                }
            }
        },
        "securitySchemes": {
            "oAuth": {
                "type": "oauth2",
                "description": "This API uses OAuth 2 with the client credentials flow.",
                "flows": {
                    "clientCredentials": {
                        "tokenUrl": "",
                        "scopes": {}
                    }
                }
            }
        }
    },
    "security": [
        {
            "oAuth": []
        }
    ]
}
